"""empty message

Revision ID: 369e9a3daaed
Revises: 
Create Date: 2019-02-09 22:37:58.210269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '369e9a3daaed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Reports', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('Reports', sa.Column('sender', sa.String(length=100), nullable=True))
    op.add_column('Reports', sa.Column('theme', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Reports', 'theme')
    op.drop_column('Reports', 'sender')
    op.drop_column('Reports', 'description')
    # ### end Alembic commands ###
